########################## Default Configuration #########################
baseURL = "https://www.joshuabooth.nz/"
languageCode = "en-us"
# site title 
title = "Joshua Booth - Full-Stack Software Developer"
# post pagination
paginate = "5"
# post excerpt
summaryLength = "10"

[markup.goldmark.renderer]
unsafe= true

[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]

########################## Plugins ###################################

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"

# js plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


########################### Navigation ###############################

# main menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "work"
name = "Work"
weight = 2

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3

# footer menu
[[menu.footer]]
URL = "about"
name = "About"
weight = 1

[[menu.footer]]
URL = "work"
name = "Work"
weight = 2

[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 3


######################### Default Parameters #########################
[params]
# home
home = "Home"
# logo
logo = "images/icons/logo.svg"
# meta data
author = "Joshua Booth"
description = "Joshua Booth, full-stack software developer passoniate about web development and design. Here on my personal website you can find all about me, my work and how to contact me."
# Google Analytics ID
googleAnalyticsID = "UA-155146153-1"
# contact form action
contactFormAction = "https://formspree.io/xyyknvro"
# copyright
copyright = "&copy; 2020 [Joshua Booth](https://joshuabooth.nz) All Rights Reserved"

# preloader
[params.preloader]
enable = true
preloader = "images/icons/logo.svg" # needs to be png, jpg, svg or gif format

# search
[params.search]
enable = false

# blog
[params.blog]
enable = false


######################## Banner ######################################
[params.banner]
bgImage = "images/banner/banner-bg.svg"
title = "Joshua Booth"
subTitle = "Design & Full-stack Development"
image = "images/banner/web_developer.svg"


######################## Call to Action ##############################
[params.cta]
enable = true
image = "images/get_in_touch.svg"
title = "Hire me for your next project"
description = ""
[params.cta.button]
enable = true
label = "Contact me"
link = "contact"


############################## Social Site ###########################
[[params.social]]
name = "Instagram"
icon = "ti-instagram" # themify icon pack https://themify.me/themify-icons
link = "https://www.instagram.com/joshuabooth.nz/"
[[params.social]]
name = "GitHub"
icon = "ti-github" # themify icon pack https://themify.me/themify-icons
link = "https://github.com/Joshua-Booth"
[[params.social]]
name = "LinkedIn"
icon = "ti-linkedin" # themify icon pack https://themify.me/themify-icons
link = "https://www.linkedin.com/in/joshua-booth/"
[[params.social]]
name = "Email"
icon = "ti-email" # themify icon pack https://themify.me/themify-icons
link = "mailto:me@joshuabooth.nz"
[[params.social]]
name = "Phone"
icon = "ti-mobile" # themify icon pack https://themify.me/themify-icons
link = "tel:027-943-4727"


############################ About ############################
[params.about]
enable = true
[params.about.cta]
enable = true
image = "images/work.svg"
title = "Websites, Software and UI Designs"
description = "Take a look at my work and portfolio"
[params.about.cta.button]
enable = true
label = "View my Portfolio"
link = "work"


############################ Skills ############################
[params.skills]
enable = true

[[params.skills.front]]
name = "HTML"
icon = "/images/about/html.svg"
[[params.skills.front]]
name = "CSS"
icon = "/images/about/css.svg"
[[params.skills.front]]
name = "JavaScript"
icon = "/images/about/javascript.svg"

[[params.skills.back]]
name = "Python"
icon = "/images/about/python.svg"
[[params.skills.back]]
name = "C#"
icon = "/images/about/csharp.svg"
[[params.skills.back]]
name = "MySQL & T-SQL"
icon = "/images/about/mysql.svg"

[[params.skills.design]]
name = "Adobe Photoshop"
icon = "/images/about/adobe-photoshop.svg"
[[params.skills.design]]
name = "Adobe Illustrator"
icon = "/images/about/adobe-illustrator.svg"
[[params.skills.design]]
name = "Adobe XD"
icon = "/images/about/adobe-xd.svg"

[[params.skills.tools]]
name = "Git & GitHub"
icon = "/images/about/git.svg"
[[params.skills.tools]]
name = "Visual Studio & Code"
icon = "/images/about/visual-studio-code.svg"