[build]
  publish = "public"
  command = "hugo"
  
[build.environment]
  HUGO_VERSION = "0.79.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404